<?php

return [
	'CyberPunk',
	'Dystopia',
	'Futuristic',
	'Sci-Fi',
	'Travel',
	'Health and Fitness',
	'Food and Cooking',
	'Personal Development',
	'Fashion',
	'Finance',
	'Parenting',
	'Home and Decor',
	'Sports',
	'Entertainment',
	'Education',
	'Business and Entrepreneurship',
	'Science',
	'Politics and Current Events',
	'Art and Creativity',
	'Lifestyle',
	'Gaming',
	'Relationships',
	'Books and Literature',
	'Self-Care and Wellness',
	'DIY and Crafts',
	'Environmental Issues',
	'Travel Tips and Guides',
	'Technology',
	'Career and Professional Development',
	'Motivation and Inspiration',
	'Photography',
	'Music',
	'Pets and Animals',
];
